### PR TITLE
Fix CuptiActivity name from tpp to cpp

### PR DESCRIPTION
**Pull request by aaronenyeshi**
Summary: There was a typo in the naming of this file when it was created causing a suffix .tpp. Fix this to .cpp.

Reviewed By: slgong-fb

Differential Revision: D37967514

Pulled By: aaronenyeshi

### CODE REVIEW

**Comment by aaronenyeshi** [comment]
Hi @robieta and @malfet  , is there a regression in the latest nightly profiler test? Our CI seems to be failing for a trivial change.
```
2022-07-19T20:00:19.7684835Z _________ TestCompareWithAutogradResult.test_profiler_api_without_gpu __________
2022-07-19T20:00:19.7685057Z 
2022-07-19T20:00:19.7685302Z self = <test_compare_with_autograd.TestCompareWithAutogradResult testMethod=test_profiler_api_without_gpu>
2022-07-19T20:00:19.7685609Z 
2022-07-19T20:00:19.7685750Z     def test_profiler_api_without_gpu(self):
2022-07-19T20:00:19.7686035Z >       self.base_profiler_api(False, True, True, False)
2022-07-19T20:00:19.7686200Z 
2022-07-19T20:00:19.7686310Z test_compare_with_autograd.py:279: 
2022-07-19T20:00:19.7686563Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2022-07-19T20:00:19.7686839Z test_compare_with_autograd.py:276: in base_profiler_api
2022-07-19T20:00:19.7687168Z     self.compare_results(log_dir, profilers_dict, use_gpu, record_shapes, with_stack)
2022-07-19T20:00:19.7687497Z test_compare_with_autograd.py:243: in compare_results
2022-07-19T20:00:19.7687779Z     self.assertTrue(line in autograd_result[key])
2022-07-19T20:00:19.7688032Z E   AssertionError: False is not true
```

**Comment by robieta** [comment]
I feel like it's probably https://github.com/pytorch/pytorch/pull/80796, but since the test give no addition information it's hard to tell.

**Comment by aaronenyeshi** [comment]
Issue seems to have started between July 14 - 18. https://github.com/pytorch/kineto/actions/workflows/tb_plugin_ci.yml

**Comment by robieta** [comment]
After some digging, my conclusion is that we should disable it. TensorBoard has no business unit testing the internals of profiler; if it wants this functionality it should be in PyTorch CI, not kineto CI.

**Comment by aaronenyeshi** [comment]
I will take a look at the TB_Plugin_CI and disable this test, I'm not sure why we are running it in TB.

**Pull request closed without merging**
