### PR TITLE
[XPU profiler] Introduce XPU profiler by following kineto plugin design

### PR DESCRIPTION
**Pull request by zejun-chen**
As XPU became a PyTorch built-in device, the profiler support is indispensable part of functionality completeness. In this PR, the XPU profiler is introduced by following kineto plugin design under libkineto/src/plugin/xpupti. The XPU profiler plugin is built on the foundation of intel PTI toolkit (https://github.com/intel/pti-gpu), and underlying SYCL runtime. The LIBKINETO_NOXPUPTI option is added to enable or disable the XPU profiler plugin during kineto build stage.

CC: @aaronenyeshi @briancoutinho @davidberard98 @sraikund16

### CODE REVIEW

**Comment by gujinghui** [comment]
@aaronenyeshi  could you help review?

The associated PR in pytorch is https://github.com/pytorch/pytorch/pull/130811

Thanks.

**Review by aaronenyeshi — CHANGES_REQUESTED** [review]
please check and fix broken CI signals

**Comment by gujinghui** [comment]
> please check and fix broken CI signals

@aaronenyeshi 





> please check and fix broken CI signals

@zejun-chen  pls. follow and fix. Thanks.

**Comment by zejun-chen** [comment]
> please check and fix broken CI signals

Hi, @aaronenyeshi 

Thank you for review 👍. Fix the CI error and wait for new CI result.
Here is our RFC for the PR: https://github.com/pytorch/kineto/issues/962
Could you help review?

Thank you.

**Comment by zejun-chen** [comment]
Hi, @aaronenyeshi 

The new CI failure is caused by the missing file cupti.h. Could you help take a look at the CI env?

```
[ 32%] Building CXX object CMakeFiles/kineto_base.dir/src/CuptiNvPerfMetric.cpp.o
[ 35%] Building CXX object CMakeFiles/kineto_base.dir/src/Demangle.cpp.o
In file included from /home/runner/work/kineto/kineto/libkineto/src/CuptiMetricApi.cpp:9:
/home/runner/work/kineto/kineto/libkineto/src/CuptiMetricApi.h:11:10: fatal error: cupti.h: No such file or directory
   11 | #include <cupti.h>
      |          ^~~~~~~~~
compilation terminated.
```

Thank you

**Comment by zejun-chen** [comment]
Hi, @aaronenyeshi 

The XPU profiler is targeting PT 2.5. Could you help review?
Thank you for any comments. :)

Thank you.

**Review by aaronenyeshi — APPROVED** [review]
Looks great! Thank you for creating a subfolder plugin/xpupti for the XPU profiler. I am happy to help merge any diffs into xpupti.

**Comment by zejun-chen** [comment]
Hi, @aaronenyeshi 

Thank you for help! Really appreciate that!
Could you help review https://github.com/pytorch/pytorch/pull/130811? It enables the build option for XPUPTI in kineto?

Thank you.

**Pull request closed without merging**
