### PR TITLE
[XPU] fix cmake can't find pti_view on Windows.

### PR DESCRIPTION
**Pull request by xuhancn**
On Windows, we need to add version number to find pti_view:
Image

Local validate passed:
image

### CODE REVIEW

**Comment by sraikund16** [comment]
@xuhancn is this ready or was it changed to draft for a specific reason?

**Comment by xuhancn** [comment]
Hi @sraikund16 we still internal discussed about if we need to get a lib list via a CMake var, we think it should be a better solution. So, I marked is as draft.

**Comment by xuhancn** [comment]
Hi @sraikund16 We discussed and decided to merge this PR. We can let it work and target to PyTorch release/2.7.
For CMake file optimization, we think it is nice to have work, and no plan for it now.
So, please help us merge this PR.

**Review by sraikund16 — APPROVED** [review]

**Review by sanrise — APPROVED** [review]
LGTM, has some minor lint flags (shown in Phabricator).

**Comment by xuhancn** [comment]
> LGTM, has some minor lint flags (shown in Phabricator).

@sanrise How to fix it?

**Pull request closed without merging**
