### PR TITLE
Continuously fetch new runs

### PR DESCRIPTION
**Pull request by TomWildenhain-Microsoft**
Fixes the issue of hanging in VS code and updates runs automatically without refresh.  The runs list should be small (has just run name, not content) and should be inexpensive to refresh.
Fix issue: https://github.com/pytorch/kineto/issues/189

### CODE REVIEW

**Review by guotuofeng — APPROVED** [review]

**Comment by Kingwl** [comment]
Sorry. May I ask why we fetch the runs forever? 

I thought we could just get any run and assume the server was ready.

**Comment by TomWildenhain-Microsoft** [comment]
> Sorry. May I ask why we fetch the runs forever?
> 
> I thought we could just get any run and assume the server was ready.
> 
> And even if we were to get it forever, it should be spaced out over a longer period (1s? I guess).

If you want it to be longer (1 sec instead of 0.1 sec) that's fine.  It fetches continuously because TB actually takes time to parse each log and makes them available as it parses them. If you only wait for non-empty runs you will often only get the first run.  We could do a back-off type strategy (delay 0.1 sec for the first 5 secs and 1 sec after).  That said, the call is not expensive (just a list of names) so I don't think the 0.1 sec frequency should be an issue.  Keep in mind that it is a 0.1 sec delay after getting a response, so if the response time is really long and exceeds 0.1 secs it won't queue up multiple requests.

**Comment by guotuofeng** [comment]
> Sorry. May I ask why we fetch the runs forever?
> 
> I thought we could just get any run and assume the server was ready.
> 
> And even if we were to get it forever, it should be spaced out over a longer period (1s? I guess).

We add support for AWS, Azure Blobs and Google Cloud. In this case, there is no guarantee when all data could be downloaded to local. From this point of view, the waiting time is undetermined.  @TomWildenhain-Microsoft's fix would fix the long loading timer when the log dir is in remote path like AWS, Azure Blobs.

**Comment by Kingwl** [comment]
Okay. got it.

/cc: @guyang3532

**Pull request merged**
