### PR TITLE
fix: cpu op correlate with runtime op

### PR DESCRIPTION
**Pull request by shinytang6**
resolves https://github.com/pytorch/kineto/issues/843

### CODE REVIEW

**Comment by shinytang6** [comment]
tb plugin ut code seems outdated, I can help fix the CI if we reach consensus on this pr

**Comment by shinytang6** [comment]
@aaronenyeshi Could you pls help take a look?

**Comment by aaronenyeshi** [comment]
This fix looks good to me, please help take a look at the CI issue.

**Comment by wizzniu** [comment]
@shinytang6 ,why not correct the "External id" just using `op.linkedActivity()->correlationID()` when `op.linkedActivity()` is True? And if do this, no need to modify the tb-plugin code.

**Comment by aaronenyeshi** [comment]
Failing tests:
```
FAILED test_profiler.py::TestProfiler::test_all_categories - AssertionError: 0 != 30
FAILED test_profiler.py::TestProfiler::test_external_id - AssertionError: 0 != 12
FAILED test_profiler.py::TestProfiler::test_gpu_utilization - AssertionError: 0 != 3
FAILED test_profiler.py::TestProfiler::test_gpu_utilization_kernel_out_of_step - AssertionError: 0 != 2
FAILED test_profiler.py::TestProfiler::test_group_by_kernel_columns - AssertionError: 0 != 3
FAILED test_profiler.py::TestProfiler::test_group_by_kernel_columns_invalid_input - AssertionError: 0 != 5
FAILED test_profiler.py::TestProfiler::test_multiple_profilersteps_no_overlap - AssertionError: 0 != 40
FAILED test_profiler.py::TestProfiler::test_no_profilerstep - AssertionError: 0 != 1
FAILED test_profiler.py::TestProfiler::test_remove_dup_nodes - AssertionError: 0 != 8
FAILED test_profiler.py::TestProfiler::test_runtime_called_by_profilerstep - AssertionError: 0 != 1
FAILED test_profiler.py::TestProfiler::test_runtime_launch_multipe_kernels - AssertionError: 0 != 253118
FAILED test_profiler.py::TestProfiler::test_self_time - AssertionError: 0 != 20
FAILED test_profiler.py::TestProfiler::test_tensor_core - AssertionError: 0 != 1.0 within 7 places (1.0 difference)
FAILED test_tensorboard_end2end.py::TestEnd2End::test_tensorboard_end2end - AssertionError: b'{"s[8505 chars]/li></ul>", "environments": [{"title": "Number[1770 chars]n"}}' != b'{"s[8505 chars]/li><li>Kernels with 68% time are launched by [2167 chars]n"}}'
FAILED test_tensorboard_end2end.py::TestEnd2End::test_tensorboard_with_path_prefix - AssertionError: b'{"s[8505 chars]/li></ul>", "environments": [{"title": "Number[1770 chars]n"}}' != b'{"s[8505 chars]/li><li>Kernels with 68% time are launched by [2167 chars]n"}}'
FAILED test_tensorboard_end2end.py::TestEnd2End::test_tensorboard_with_symlinks - AssertionError: b'{"s[8505 chars]/li></ul>", "environments": [{"title": "Number[1770 chars]n"}}' != b'{"s[8505 chars]/li><li>Kernels with 68% time are launched by [2167 chars]n"}}'
```

**Review by aaronenyeshi — CHANGES_REQUESTED** [review]
Please check failing unit tests

**Comment by shinytang6** [comment]
Sorry for the late reply. Currently, l don't have cuda env and much time to continue the work, any interested developers are welcome to continue this fix.

**Comment by shinytang6** [comment]
> @shinytang6 ,why not correct the "External id" just using `op.linkedActivity()->correlationID()` when `op.linkedActivity()` is True? And if do this, no need to modify the tb-plugin code.

@wizzniu good point, but l'm not sure if there's any compatiblilty issue since this issue seems occurring in pytorch 2.0.0+ only

**Comment by aaronenyeshi** [comment]
Another fix landed in https://github.com/pytorch/kineto/pull/873, closing this PR.

**Pull request closed without merging**
