### PR TITLE
optimize memory view using lttb sample

### PR DESCRIPTION
**Pull request by lh-ycx**
Enhancement for Issue #760.

Hey guys, I've optimized the speed of the memory view using the LTTB sampling (Largest-Triangle-Three-Buckets sampling, which is able to downsample time series–like data while retaining the overall shape and variability in the data).

I've tested this using a PyTorch profiler trace of 2G, and the memory view page will not get crashed and the scaling operation is smooth and rather acceptable to me.

### CODE REVIEW

**Comment by lh-ycx** [comment]
@chaekit @aaronenyeshi I checked the failed test (test_tensorboard_end2end.py). This test compares the response from the tensorboard frontend with the manually generated and verified `result_check_file.txt`. 

Since the memory curve has been sampled, it cannot match the previous manually generated result. As a result, the test fails.

Shall I regenerate the `result_check_file.txt`? Or, is there any other method to let the test pass?

**Comment by lh-ycx** [comment]
OK, I'll work on it this week.

**Comment by lh-ycx** [comment]
Hi, @aaronenyeshi. Sorry for the late response.

**CI failures**

I've carefully checked the test case and found that the test would always fail in Python 3.9 and 3.10 (please refer to #785). I also find my commit is consistent with the content in `result_check_file.txt`. So there is no need to regenerate the file. Could you please rerun the CI? Thanks a lot.

**Screenshots of the before and after views**

I use a 329M trace to show the before and after views as well as the memory footprint. (A larger trace (up to GBs) can be selected but the unoptimized view would crash.)

Before view:
image

After view:
image

Before memory footprint:
image

After memory footprint:
image

**Review by aaronenyeshi — APPROVED** [review]
LGTM, the previous CI issues were unrelated to the changes in this diff.

**Pull request closed without merging**
