### PR TITLE
Fix Config's destruction order issue

### PR DESCRIPTION
**Pull request by dzhulgakov**
The previous trick with `weak_ptr` didn't work on its own and led to crashes like in https://github.com/pytorch/pytorch/pull/89174 . This seems to be sufficient to guarantee lifetime even though it still accesses destroyed `weak_ptr` instance which is technically UD. A more proper fix would probably be to pass FactoryMap as Config constructor, but it's a more involved refactoring.

### CODE REVIEW

**Review by robieta — APPROVED** [review]
LGTM

**Review by aaronenyeshi — APPROVED** [review]
Thank you very much for this fix! Looks like it was not common for the config update thread to wake and reference a destroyed config factory until nvfuser unit tests. Let's land it! :)

**Comment by aaronenyeshi** [comment]
Since this is merged, is there a submodule update in pytorch/pytorch, you'd like us to accept?

**Comment by dzhulgakov** [comment]
Looks like @robieta is on it with https://github.com/pytorch/pytorch/pull/89846 (and automated submodule updates are back)

**Pull request closed without merging**
