### PR TITLE
libkineto: Fix various compiler errors with mingw-w64 based toolchain

### PR DESCRIPTION
**Pull request by Biswa96**

### CODE REVIEW

**Comment by Kreijstal** [comment]
Thank you, I was having trouble compiling this under mingw

**Comment by briancoutinho** [comment]
thanks for adding the fix 👍

**Review by aaronenyeshi — APPROVED** [review]
LGTM

**Comment by Biswa96** [comment]
It would be helpful if the linter CI runs in public GitHub actions. Or at least the CI log should be accessible to everyone.

**Comment by aaronenyeshi** [comment]
> It would be helpful if the linter CI runs in public GitHub actions. Or at least the CI log should be accessible to everyone.

I agree. I checked the lints, and clang-tidy seems to want to remove these two lines in ThreadUtil.cpp.
```
#include <sys/syscall.h>
#include <sys/types.h>
```

**Pull request closed without merging**
