### PR TITLE
Small updates to tb_plugin_ci

### PR DESCRIPTION
**Pull request by malfet**
- Print git version of installed packages
- Rename 1.9rc into 1.10rc
- Stop testing python-3.6 (as its EOLed)

### CODE REVIEW

**Review by aaronenyeshi — APPROVED** [review]
LGTM! Thank you for this change

**Comment by aaronenyeshi** [comment]
Could you please point me to the location in the logs that shows the pytorch git_version? Thank you
https://github.com/pytorch/kineto/runs/4875305789?check_suite_focus=true

**Comment by aaronenyeshi** [comment]
> Could you please point me to the location in the logs that shows the pytorch git_version? Thank you https://github.com/pytorch/kineto/runs/4875305789?check_suite_focus=true

Nvm, I was able to find it in the raw logs. Thanks:
```
2022-01-19T23:20:17.8343351Z Successfully installed torch-1.11.0.dev20220119+cpu
2022-01-19T23:20:18.0249047Z + pip install --pre torchvision --no-deps -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
2022-01-19T23:20:18.4711691Z Looking in links: https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
2022-01-19T23:20:19.2966367Z Collecting torchvision
2022-01-19T23:20:19.3054456Z   Downloading https://download.pytorch.org/whl/nightly/cpu/torchvision-0.12.0.dev20220119%2Bcpu-cp39-cp39-linux_x86_64.whl (17.3 MB)
2022-01-19T23:20:19.6982444Z Installing collected packages: torchvision
2022-01-19T23:20:20.3753395Z Successfully installed torchvision-0.12.0.dev20220119+cpu
2022-01-19T23:20:20.5449114Z + python -c import torch; print(torch.__version__, torch.version.git_version); from torch.autograd import kineto_available; print(kineto_available())
2022-01-19T23:20:21.2544733Z 1.11.0.dev20220119+cpu 1eb6146d967b2d09af37c54af411d03f0b790209
2022-01-19T23:20:21.2545068Z True
```

**Comment by malfet** [comment]
@aaronenyeshi yeah, let me report issue to github that logs are never loaded

**Pull request closed without merging**
