### PR TITLE
Fix misaligned order of baseline-Ops and exp-Ops in DIFF view

### PR DESCRIPTION
**Pull request by wizzniu**
fix https://github.com/pytorch/kineto/issues/881

Summary:
1. Update the version of Nodejs in `fe/README.md` since Node.js 16x is too old and not in maintenance.
2. Update some dependencies in `fe/package.json` and `fe/yarn.lock` to make building successful.
3. When generating data source from underlying data in `DiffOverview.tsx`, modify the alignment order of baseline and exp using op's name instead of index.
4. Replace `index.html` in `torch_tb_profiler/static` with newly generated to update tensorboard UI.

### CODE REVIEW

**Comment by wizzniu** [comment]
fix https://github.com/pytorch/kineto/issues/881

**Comment by wizzniu** [comment]
@aaronenyeshi Could you plz help review this?

**Comment by aaronenyeshi** [comment]
> @aaronenyeshi Could you plz help review this?

Overall, this looks good. Would it be okay to add more details in the body of this PR/commit? Explaining what the changes are and why. Also, can you please share before and after fix examples? Thank you!

**Comment by wizzniu** [comment]
> > @aaronenyeshi Could you plz help review this?
> 
> Overall, this looks good. Would it be okay to add more details in the body of this PR/commit? Explaining what the changes are and why. Also, can you please share before and after fix examples? Thank you!

Have added details at the beginning of this PR. And the effect after fixing this bug can be found in https://github.com/pytorch/kineto/issues/881

**Review by aaronenyeshi — APPROVED** [review]
Great! Thank you!

**Pull request closed without merging**
