### PR TITLE
To support extend Profiler

### PR DESCRIPTION
**Pull request by xunsongh**
With this patch, the kineto will be able to support extend profiler to register themselves and co-work with kineto's tracing strategy. In this patch, we made three important changes in kineto.

1. The middle level has been abstracted as an abstract class - ActivityProfilerBase. All profiler instantiations inside or outside the kineto will inherit this class with overriding necessary APIs. Detailed design for this structure please refer to this [RFC](https://github.com/pytorch/kineto/issues/647)

2. The DeviceType enum class has been added to include/ as same as ActivityType. This enum class will make the profiler controller be enabled to choose integrated or extend path for instantiating the profiler_. This argument will be passed via front APIs such as initProfilerIfRegistered, which called by PyTorch.

3. A simple hook has been added into include/libkineto.h, with the hook function - registerExtendProfiler. This hook enables extend plug-ins such as Intel® Extension for PyTorch* to register extend profiler into kineto and override the constructor of profiler_ in controller which inherit the abstract class - ActivityProfilerBase described above.

* Any questions with this patch please contact Xunsong, Huang (xunsong.huang@intel.com)

Signed-off-by: Xunsong, Huang <xunsong.huang@intel.com>

### CODE REVIEW

**Comment by gujinghui** [comment]
@aaronenyeshi  @chaekit @gdankel @robieta @briancoutinho

Could you help review and give suggestions? Thanks.

**Comment by aaronenyeshi** [comment]
This looks good, can you please help rebase on main, and I will run some internal checks?

**Comment by briancoutinho** [comment]
@xunsongh  there already is an activity profiler and activity profiler session base class. Can we please use that instead of introducing another way to add plugins??? 
https://github.com/pytorch/kineto/blob/main/libkineto/include/IActivityProfiler.h#L73-L117

This will likely break any other use-cases of the other activity profiler plugin extension interface.

**Comment by xunsongh** [comment]
> [xunsongh](https://github.com/xunsongh) You are right actually, it won't break any existing features 👍 Although, I think this leads to two ways to extend Kineto activity profiler - one using IActivityProfiler that is a plugin based , and another using ActivityProfilerBase.
> 
> Currently the codes somewhere between a refactor, @gdankel was adding a change to split up ActivityProfiler into two - one core composite profiler with all management logic and a set of plugins - like CuptActivityProfiler, CuptiRangeProfiler. (Cupti Range profiler is a plugin example - https://github.com/pytorch/kineto/blob/main/libkineto/src/CuptiRangeProfiler.h)
> 
> We can use the current approach and eventually merge ActivityProfilerBase with IactivityProfilerSession, would that be okay?

That's a good news to know that someone is working on decoupling the ActivityProfiler. And I think the purposes of us are similar to each other. There is only one suggestion or requirement from me that we wish more abstract API in high level abstract class (IActivitySession) besides `start`, `stop` and `processTrace`. For example, we are looking forward to changing runtime configures for each tracer. And also, we suppose the kineto could handle the out-of-queue scheme. We are still discussing these requirements inside Intel and will offer a complete requirements list to you.

And then the most necessary thing is, I need to be noticed when your changes of spliting up ActivityProfiler will done and which branch to trace those changes. I wish to exchange any information on this topic with you in time.

**Comment by gdankel** [comment]
> That's a good news to know that someone is working on decoupling the ActivityProfiler. And I think the purposes of us are similar to each other. There is only one suggestion or requirement from me that we wish more abstract API in high level abstract class (IActivitySession) besides `start`, `stop` and `processTrace`. For example, we are looking forward to changing runtime configures for each tracer. And also, we suppose the kineto could handle the out-of-queue scheme. We are still discussing these requirements inside our team and will offer a complete requirements list to you.

While Kineto supports arbitrary configuration, it is not currently exposed to PyTorch. What sort of configuration did you have in mind?

What do you mean by out-of-queue scheme?

> And then the most necessary thing is, I need to be noticed when your changes of spliting up ActivityProfiler will done and which branch to trace those changes. I wish to exchange any information on this topic with you in time.

#698 lays the groundwork for the splitting up of ActivityProfiler, but the actual split is for a later patch. And there are three things to split out: CUPTI specific, ROCm specific and PyTorch specific. The refactoring mostly focuses on splitting out the PyTorch specific code. But that should still help with adding support for new devices.

**Review by aaronenyeshi — CHANGES_REQUESTED** [review]
not sure where to go from here, refactoring #698 is too risky as it may cause breakage internally. Maybe we should support XPU the same way we support AMD? cc @gdankel @briancoutinho

**Comment by xunsongh** [comment]
> not sure where to go from here, refactoring #698 is too risky as it may cause breakage internally. Maybe we should support XPU the same way we support AMD? cc @gdankel @briancoutinho

Hi, @aaronenyeshi 

I apologize for not having updated or kept track of this PR until now. The reason I have not closed this PR is that there is still a requirement on our end to enable Kineto support for the XPU backend. However, based on in-depth discussions with the Kineto developers and drawing from my personal development experience over the past months, I am planning to approach the integration of XPU backend support in a different manner than what was proposed in the original PR.

My colleagues are currently developing a standalone PTI-sdk library, and we hope that in the future, Kineto could integrate our library in a similar fashion to how it integrates CUPTI or Roctracer. This would ideally allow for full support of the XPU backend with minimal modifications. In approximately one to two months, I intend to submit a new RFC and accompanying PR with revised code for discussion.

For now, I will close this PR to prevent any confusion.

Thank you for your understanding.

**Pull request closed without merging**
