### PR TITLE
clearing cached data, causing memory leak

### PR DESCRIPTION
**Pull request by ramcherukuri**
This will fix the test test_cuda.py::TestCuda::test_cuda_memory_leak_detection failure.

### CODE REVIEW

**Comment by aaronenyeshi** [comment]
@ramcherukuri can you please sign the Facebook CLA, to pass that check?

**Review by aaronenyeshi — APPROVED** [review]
LGTM, thank you for the fix!

**Comment by ramcherukuri** [comment]
> @ramcherukuri can you please sign the Facebook CLA, to pass that check?

Done

**Pull request closed without merging**
